### ISSUE TITLE
[question] aarch64 support?

### ISSUE THREAD

**Issue by GoAlexander** [CODeRUS/github-sfos-build#1]
Hi @CODeRUS ,
Thanks for the all your work. Do you have any plans to add aarch64 build to the CI? Is it possible?

I was not in active support for Sailfish OS long time so sorry I don't know current state of aarch64...

**Comment by CODeRUS** [comment]
hi, i built aarch64 images https://github.com/CODeRUS/docker-sailfishos-platform-sdk/blob/master/Dockerfile.all but failed to deploy rpm package build with my target to device due to weird problems with aarch linking. And i do not own aarch64 device myself, so someone is have to try to fix problems.

**Comment by GoAlexander** [comment]
Ok, thanks for clarification. Should I close the issue?

**Comment by CODeRUS** [comment]
i can do it for you :)
